name: Notify BTC

on:
  schedule:
    - cron: "*/15 * * * *"   # roda a cada 15 min
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests pandas matplotlib pytz

      - name: Run notify_btc.py
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python notify_btc.py
