name: BTC notify (Telegram)

on:
  schedule:
    # horários em UTC (America/Cuiabá é UTC-4)
    - cron: '0 10 * * *'   # 06h (Cuiabá)
    - cron: '0 17 * * *'   # 13h (Cuiabá)
    - cron: '0 0 * * *'    # 20h (Cuiabá)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests
      - name: Run notifier
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python notify_btc.py
       - name: Commit histórico
         run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add btc_history.csv
          git commit -m "Atualiza histórico BTC [skip ci]" || echo "Nada para commitar"
          git push
